#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


SCHEMA = "murmurmark.review_profile_lineage/v1"
LINEAGE_REQUIRED_TRANSCRIBE_VERSION = (0, 3, 1)


def sha256_file(path: Path) -> str | None:
    if not path.is_file():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def relative_path(path: Path, session: Path) -> str:
    try:
        return str(path.resolve().relative_to(session.resolve()))
    except ValueError:
        return str(path.resolve())


def artifact(path: Path, session: Path) -> dict[str, Any]:
    return {
        "path": relative_path(path, session),
        "size": path.stat().st_size if path.is_file() else None,
        "sha256": sha256_file(path),
    }


def resolve_artifact_path(session: Path, value: Any) -> Path | None:
    if not isinstance(value, str) or not value:
        return None
    path = Path(value).expanduser()
    return path if path.is_absolute() else session / path


def build_lineage(
    *,
    session: Path,
    input_profile: str,
    output_profile: str,
    dialogue_path: Path,
    quality_path: Path,
    previous_report: dict[str, Any] | None,
) -> dict[str, Any]:
    previous_lineage = previous_report.get("lineage") if isinstance(previous_report, dict) else None
    if input_profile == output_profile and isinstance(previous_lineage, dict):
        return previous_lineage
    return {
        "schema": SCHEMA,
        "base_input_profile": input_profile,
        "artifacts": {
            "clean_dialogue": artifact(dialogue_path, session),
            "quality_report": artifact(quality_path, session),
        },
    }


def _version_tuple(value: Any) -> tuple[int, ...]:
    parts: list[int] = []
    for item in str(value or "").split("."):
        if not item.isdigit():
            break
        parts.append(int(item))
    return tuple(parts)


def _transcribe_requires_lineage(session: Path) -> bool:
    path = session / "derived/transcript-simple/whisper-cpp/resolved/transcribe_simple_report.json"
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    generator = report.get("generator") if isinstance(report, dict) else None
    version = generator.get("version") if isinstance(generator, dict) else None
    return _version_tuple(version) >= LINEAGE_REQUIRED_TRANSCRIBE_VERSION


def review_profile_is_current(session: Path, report: dict[str, Any] | None) -> bool:
    if not isinstance(report, dict):
        return False
    lineage = report.get("lineage")
    if not isinstance(lineage, dict):
        # Reports written before lineage support remain compatible until their
        # base transcript is regenerated by a lineage-aware transcriber.
        return not _transcribe_requires_lineage(session)
    if lineage.get("schema") != SCHEMA:
        return False
    artifacts = lineage.get("artifacts")
    if not isinstance(artifacts, dict):
        return False
    for name in ("clean_dialogue", "quality_report"):
        expected = artifacts.get(name)
        if not isinstance(expected, dict):
            return False
        path = resolve_artifact_path(session, expected.get("path"))
        if path is None or not path.is_file():
            return False
        if expected.get("size") != path.stat().st_size:
            return False
        if expected.get("sha256") != sha256_file(path):
            return False
    return True
